### ISSUE TITLE
Diffuse response calculation in LATAnalysisScripts

### ISSUE THREAD

**Issue by astro-fermi** [kialio/LATAnalysisScripts#5]
Hi,

Does current version of LATAnalysisScripts compute diffuse response (gtdiffrsp)? Actually, while running unbinned likelihood, I found an extended source in FoV and while fitting I got following error-
Diffuse component p7source_v6__ic443 does not have an associated diffuse response.
I searched and found that gtdiffrsp has to be run before fitting to avoid this error.

How can I compute diffuse response in LATAnalysisScripts?
Please help.
Thanks.
-- Vaidehi

**Comment by kialio** [comment]
The gtdiffrsp calculation is not built into the LATAnalysisScripts package since it's pretty rare that you actually need to do it.  I'll put in an issue request to add it so I don't forget though.

If you do run it, I suggest using the method in gtapps_mp since computing the diffuse response columns takes a long time.
